//! Builds the stand-in bridge: reads the recordings, works out what call each one can answer, and
//! compiles `src/stub.rs` into an executable with that table baked in.
//!
//! Which recordings a wire verb may answer from comes from the `examples` of its spec in
//! `docs/specs/`, plus [`REPLAY_EXTRA`] for recordings no spec lists yet. That is the rule
//! pyMzLib's `pkg/src/conftest.py` follows, so a recording that is a spec's example answers the same
//! call in every binding.
//!
//! All JSON handling happens here, at build time, so the executable is std-only and compiles in
//! well under a second. It is compiled by invoking the same `rustc` that is building this crate,
//! because Cargo cannot build a dependency's binary target for a doctest to run.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::Command;

use serde_json::Value;

/// Recordings for verbs whose spec does not list them as an example, or that have no spec yet.
///
/// Mirrors `REPLAY_EXTRA` in pyMzLib's `pkg/python/src/conftest.py`, plus the one recording only
/// this crate has (`pride ftp-files`). When a verb's spec lands with one of these among its
/// `examples`, delete it here.
const REPLAY_EXTRA: &[(&str, &[&str])] = &[
    ("readers read-spectra", &["readers_spectra_ms2.json"]),
    ("readers read-features", &["readers_features_topfd.json"]),
    (
        "readers read-matches",
        &[
            "readers_matches_casanovo.json",
            "readers_matches_mspathfinder.json",
            "readers_matches_mzid.json",
            // --scores: the bridge's checker cannot hold a present_when column to a spec example.
            "readers_matches_mzid_scores.json",
        ],
    ),
    // The identify bulk shape is not a spec example: check_verbs.py has no table-less bulk verb.
    ("readers identify", &["readers_many_identify.json"]),
    ("version", &["bridge_version.json"]),
    ("pride files", &["pride_PXD000001_files.json"]),
    ("pride ftp-files", &["pride_ftp_PXD000001.json"]),
    ("pride search", &["pride_search_plasmodium.json"]),
    ("quant flashlfq", &["flashlfq_small.json"]),
    ("quant median-polish", &["median_polish_small.json"]),
    ("peptidoform fragments", &["peptidoform_P02768_small.json"]),
];

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let root = manifest.join("..").join("..");
    let specs = root.join("docs").join("specs");
    let fixtures = root.join("tests").join("fixtures");
    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap());

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/stub.rs");
    println!("cargo:rerun-if-changed={}", specs.display());
    println!("cargo:rerun-if-changed={}", fixtures.display());

    let table = replay_table(&specs);
    let recordings = out.join("recordings");
    std::fs::create_dir_all(&recordings).unwrap();

    let mut code = String::from(
        "// Generated by tools/replay-bridge/build.rs. Do not edit.\n\
         pub static TABLE: &[(&str, &[Recording])] = &[\n",
    );
    for (verb, names) in &table {
        writeln!(code, "    ({verb:?}, &[").unwrap();
        for name in names {
            let path = fixtures.join(name);
            let text = std::fs::read_to_string(&path).unwrap_or_else(|error| {
                panic!(
                    "the replay table names fixture {name} for '{verb}', which cannot be read at \
                     {}: {error}",
                    path.display()
                )
            });
            let parsed: Value = serde_json::from_str(&text)
                .unwrap_or_else(|error| panic!("{name} is not JSON: {error}"));
            // A fixture is either the bare `data` payload or a whole envelope.
            let data = match &parsed {
                Value::Object(map) if map.contains_key("ok") && map.contains_key("data") => {
                    map["data"].clone()
                }
                other => other.clone(),
            };
            let envelope = serde_json::json!({"ok": true, "data": data, "error": null});
            let envelope_path = recordings.join(name);
            std::fs::write(&envelope_path, envelope.to_string()).unwrap();
            code.push_str(&recording(name, &data, &envelope_path));
        }
        code.push_str("    ]),\n");
    }
    code.push_str("];\n");

    let table_path = out.join("table.rs");
    std::fs::write(&table_path, code).unwrap();

    compile_stub(&manifest.join("src").join("stub.rs"), &table_path, &out);
}

/// Wire verb -> the recordings it may answer from, in a stable order.
fn replay_table(specs: &Path) -> BTreeMap<String, Vec<String>> {
    let mut table: BTreeMap<String, Vec<String>> = BTreeMap::new();
    let mut entries: Vec<PathBuf> = std::fs::read_dir(specs)
        .unwrap_or_else(|error| panic!("cannot read {}: {error}", specs.display()))
        .map(|entry| entry.unwrap().path())
        .filter(|path| path.extension().is_some_and(|ext| ext == "yaml"))
        .collect();
    entries.sort();

    for path in entries {
        // A line scan rather than a YAML parser: the two keys needed are one per line in every
        // spec (`verb:` at the top level, `fixture:` in each example), and a build dependency on a
        // YAML crate would be the only reason to have one.
        let text = std::fs::read_to_string(&path).unwrap();
        let mut verb = None;
        for line in text.lines() {
            if let Some(rest) = line.strip_prefix("verb:") {
                verb = Some(rest.split('#').next().unwrap().trim().to_owned());
            } else if let Some(rest) = ["- fixture:", "- {fixture:", "fixture:"]
                .iter()
                .find_map(|key| line.trim_start().strip_prefix(key))
            {
                let name = rest
                    .split([',', '}'])
                    .next()
                    .unwrap()
                    .trim()
                    .trim_matches(|c| c == '"' || c == '\'');
                let verb = verb
                    .clone()
                    .unwrap_or_else(|| panic!("{}: fixture before verb", path.display()));
                push_unique(table.entry(verb).or_default(), name);
            }
        }
    }
    for (verb, names) in REPLAY_EXTRA {
        for name in *names {
            push_unique(table.entry((*verb).to_owned()).or_default(), name);
        }
    }
    table
}

fn push_unique(list: &mut Vec<String>, name: &str) {
    if !list.iter().any(|existing| existing == name) {
        list.push(name.to_owned());
    }
}

/// One `Recording { .. }` literal: the envelope, plus the facts `stub.rs` checks a call against.
fn recording(name: &str, data: &Value, envelope: &Path) -> String {
    let empty = serde_json::Map::new();
    let map = data.as_object().unwrap_or(&empty);

    let mut fields = String::new();
    for (key, value) in map {
        let literal = match value {
            Value::Null => "V::Null".to_owned(),
            Value::Bool(flag) => format!("V::Bool({flag})"),
            Value::String(text) => format!("V::Text({text:?})"),
            Value::Number(number) => format!("V::Text({:?})", number.to_string()),
            Value::Array(_) | Value::Object(_) => "V::Compound".to_owned(),
        };
        write!(fields, "({key:?}, {literal}), ").unwrap();
    }

    // BULK.md: a --paths-stdin call has its own envelope. A recording is bulk when it carries the
    // per-input files[] (entries with a path) and no top-level path. `pride files` also has a
    // files list, of PRIDE files, which carry no path.
    let bulk = match map.get("files") {
        Some(Value::Array(files)) => {
            files
                .iter()
                .all(|f| f.as_object().is_some_and(|f| f.contains_key("path")))
                && !map.contains_key("path")
        }
        _ => false,
    };

    // Python's data.get("record_count", data.get("row_count")): a present-but-null record_count
    // wins over row_count.
    let total = match map.get("record_count") {
        Some(value) => value.as_u64(),
        None => map.get("row_count").and_then(Value::as_u64),
    };
    let window = match (total, map.get("returned_count").and_then(Value::as_u64)) {
        (Some(total), Some(returned)) => {
            let offset = map.get("offset").and_then(Value::as_u64).unwrap_or(0);
            format!("Some(({total}, {returned}, {offset}))")
        }
        _ => "None".to_owned(),
    };

    format!(
        "        Recording {{ fixture: {name:?}, envelope: include_str!({path:?}), fields: &[{fields}], \
         bulk: {bulk}, window: {window} }},\n",
        path = envelope.display().to_string(),
    )
}

fn compile_stub(source: &Path, table: &Path, out: &Path) {
    let exe = out.join(if cfg!(windows) {
        "mzlib-replay-bridge.exe"
    } else {
        "mzlib-replay-bridge"
    });
    let rustc = std::env::var("RUSTC").unwrap_or_else(|_| "rustc".to_owned());
    let target = std::env::var("TARGET").unwrap();

    let status = Command::new(rustc)
        .args(["--edition=2021", "--crate-name", "mzlib_replay_bridge"])
        .args(["--crate-type=bin", "--cap-lints=allow"])
        .args(["-C", "opt-level=0", "-C", "debuginfo=0"])
        .args(["--target", &target])
        .arg(source)
        .arg("-o")
        .arg(&exe)
        .env("MZLIB_REPLAY_TABLE", table)
        .status()
        .expect("could not run rustc to build the replay bridge");
    assert!(status.success(), "rustc failed to build the replay bridge");

    println!("cargo:rustc-env=MZLIB_REPLAY_BRIDGE={}", exe.display());
}
